### ISSUE TITLE
Is this possible to use in an IOS app?

### ISSUE THREAD

**Issue by 1guzzy** [AlwaysRightInstitute/SwiftyWasmer#4]
I want to use a library compiled to web assembly  in an IOS app / XCode project and I'm having a hard time figuring it out.

Thanks!

**Comment by helje5** [comment]
Not sure Wasmer comes w/ an interpreter, which would be required for App Store distribution (JITs are AFAIK not allowed). I think Wasmer can also compile to a dylib, if you have the Wasm module AOT.
You might be able to just use JavaScriptCore for that.

Anyways, not an issue specific to SwiftyWasmer.
